### PR TITLE
made production ready

### PR DESCRIPTION
**Pull request by abhisuri97**

### CODE REVIEW

**Review by sandlerben — CHANGES_REQUESTED** [review]
sorry not gonna fly, too much diff

**Comment by abhisuri97** [comment]
@sandlerben the diffs are all just from moving files. the only main changes are a few files.

**Comment by abhisuri97** [comment]
bump

**Comment by sandlerben** [comment]
My comment was a joke btw. Please merge.

**Comment by abhisuri97** [comment]
I don't have write access atm

**Comment by jondubin** [comment]
@abhisuri97 you do now :')

**Pull request merged**
